on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false # Failure in one platform build won't impact the others
      matrix:
        build:
          - name: 'dbisous-linux'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'dbisous.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'dbisous'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: build app
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.24'
          node-version: '22.x'
